### 1. Criar um array com 10 números inteiros aleatórios entre 1 e 50 e calcular a média e o desvio padrão

In [0]:
import numpy as np 

# Criar array com 10 números inteiros aleatórios entre 1 e 50, especificando a quantidade no 'size'
arr = np.random.randint(1, 51, size=10)

print('Array de números: ',arr)

# Calcular a média
media = np.mean(arr)

# Calcular o desvio padrão
desvio_padrao = np.std(arr)

print('\nMédia: ', media)
print(f'Desvio padrão: {desvio_padrao:.2f}')

Array de números:  [50 50 11 41 16  9 45 20  3 44]

Média:  28.9
Desvio padrão: 17.77


### 2. Criar um array de 10 números aleatórios e calcular a raiz quadrada de todos os valores menores ou iguais a 0,5

In [0]:
# Criar array com 10 números aleatórios
arr = np.random.rand(10)

print('Array original: ', arr)

# Filtrar os números menores ou igual 0.5
numeros_filtrados = arr[arr <= 0.5]

# Calcular a raiz quadrada
raizes_quadradas = np.sqrt(numeros_filtrados)

print('\nNúmeros filtrados:', numeros_filtrados)
print('\nRaízes quadradas dos números filtrados:', raizes_quadradas)

Array original:  [0.55711387 0.78491417 0.80118677 0.02676288 0.84123862 0.83172946
 0.75108431 0.77532441 0.2926171  0.8961134 ]

Números filtrados: [0.02676288 0.2926171 ]

Raízes quadradas dos números filtrados: [0.16359365 0.54094094]


### 3. Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios e exibir o valor máximo de cada linha de cada matriz 2D dentro dessa matriz 3D

In [0]:
# Criar matriz 3D 3x3x3x com valores aleatórios 
matriz_3d = np.random.rand(3, 3, 3)

print('Matriz 3D:')
print(matriz_3d)

# Calcular o valor máximo de cada coluna de cada matriz 2D
valores_maximos = np.max(matriz_3d, axis=1)

print('\nValor máximo de cada linha de cada matriz 2D:')
print(valores_maximos)

Matriz 3D:
[[[0.17909638 0.68354757 0.02756966]
  [0.83945771 0.30267312 0.36879951]
  [0.41454604 0.12788106 0.99198434]]

 [[0.20497153 0.7578655  0.47350745]
  [0.61347345 0.38205719 0.19549047]
  [0.64646347 0.6201932  0.91090715]]

 [[0.50068233 0.75566211 0.22757865]
  [0.53311492 0.69734871 0.04516473]
  [0.12220821 0.86928115 0.52344163]]]

Valor máximo de cada linha de cada matriz 2D: 
[[0.83945771 0.68354757 0.99198434]
 [0.64646347 0.7578655  0.91090715]
 [0.53311492 0.86928115 0.52344163]]


### 4. Criar uma matriz de tamanho 5x5 com valores aleatórios e subtrair a média de cada linha dessa matriz

In [0]:
# Criar matriz 
matriz = np.random.rand(5, 5)

print('Matriz original:')
print(matriz)

# Calcular a média
# axis = 1 -> Linha
# axis = 0 -> Coluna
medias = np.mean(matriz, axis=1)

# Subtrarir a média de cada linha
matriz_media_subtraida = matriz - medias[:, np.newaxis]

print('\nMédia de cada linha: ', medias)
print('\nMatriz com a média subtraída:')
print(matriz_media_subtraida)

Matriz original:
[[0.03587063 0.60766811 0.10620842 0.84969148 0.70287612]
 [0.41198708 0.57060942 0.70304954 0.71820932 0.82084989]
 [0.89797775 0.18198987 0.00425211 0.59093988 0.244645  ]
 [0.41806517 0.98122113 0.53177688 0.33862376 0.63361382]
 [0.9467106  0.76984726 0.85425487 0.35447802 0.06736404]]

Média de cada linha:  [0.46046295 0.64494105 0.38396092 0.58066015 0.59853096]

Matriz com a média subtraída:
[[-0.42459232  0.14720516 -0.35425453  0.38922852  0.24241317]
 [-0.23295397 -0.07433163  0.05810849  0.07326827  0.17590884]
 [ 0.51401683 -0.20197106 -0.37970881  0.20697896 -0.13931592]
 [-0.16259498  0.40056098 -0.04888327 -0.24203639  0.05295366]
 [ 0.34817964  0.1713163   0.25572391 -0.24405293 -0.53116692]]


In [0]:
# Conferindo 
(0.03587063 + 0.60766811 + 0.10620842 + 0.84969148  + 0.70287612) / 5

Out[11]: 0.460462952

In [0]:
# Conferindo 
0.03587063 - 0.460462952

Out[12]: -0.42459232199999997

### 5. Criar uma matriz de tamanho 4x4 com valores aleatórios e calcular a média e o desvio padrão das diagonais da matriz

In [0]:
# Criar matriz 
matriz = np.random.rand(4,4)

print('Matriz:') 
print(matriz)

diag_principal = np.diag(matriz)
diag_secundaria = np.diag(np.fliplr(matriz))

# Calcular a média
media_diagonal = np.mean([diag_principal, diag_secundaria])

# Calcular o desvio padrão
desvio_diagonal = np.std([diag_principal, diag_secundaria])

print('\nDiagonal principal: ', diag_principal)
print('\nDiagonal secundária: ', diag_secundaria)
print('\nMédia das diagonais: ', media_diagonal)
print('\nDesvio padrão das diagonais: ', desvio_diagonal)

Matriz:
[[0.8439995  0.46864898 0.4669707  0.83867096]
 [0.60962507 0.13945156 0.79149692 0.45422642]
 [0.47801783 0.22918674 0.23932578 0.02118961]
 [0.54205086 0.21518571 0.99922554 0.07921295]]

Diagonal principal:  [0.8439995  0.13945156 0.23932578 0.07921295]

Diagonal secundária:  [0.83867096 0.79149692 0.22918674 0.54205086]

Média das diagonais:  0.4629244102630059

Desvio padrão das diagonais:  0.3076368398854149


In [0]:
# Anotações 
# Entendendo os eixos 

matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

soma_eixo_0 = np.sum(matriz, axis=0)
print(soma_eixo_0)

# Eixo 0 -> 1 + 7 + 4 (Coluna)

[12 15 18]


In [0]:
soma_eixo_1 = np.sum(matriz, axis=1)
print(soma_eixo_1)

# Eixo 1 -> 1 + 2 + 3 (Linha)

[ 6 15 24]


In [0]:
# Tipos de matrizes

matriz_1d = np.array([1, 2, 3, 4, 5])

matriz_2d = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

matriz_3d = np.array([[[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]],
                      [[10, 11, 12],
                       [13, 14, 15],
                       [16, 17, 18]],
                      [[19, 20, 21],
                       [22, 23, 24],
                       [25, 26, 27]]])